FROM ubuntu as builder
RUN apt-get update -y && apt-get install openjdk-17-jdk -y && apt-get install maven -y && apt-get install git -y
RUN git clone https://github.com/harsh-jaiswal-21/student-ui.git
WORKDIR ./student-ui
RUN mvn clean install

FROM tomcat:jre8-alpine
COPY --from=builder ./student-ui/target/*.war /usr/local/tomcat/webapps/student.war
